name: Custom Security Action for CI
description: custom action for image security

inputs:

  image_name:
    reuired: true

  image_tag: 
    required: false
    default: latest

  docker_username:
    required: true

  docker_token: 
    required: true

runs: 
    using: composite
    steps:
      - name: docker login
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: docker vuln security scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ vars.DOCKER_USERNAME }}/${{ inputs.image_name }}:v${{ inputs.image_tag }}
          format: "table"
          vuln-types: "os,library"
          scanners: "vuln"
          ignored-unfixed: "true"
          severity: "CRITICAL"
          exit-code: "0"
          outputs: security_scan.txt
        
      - uses: actions/upload-artifact@v7
        with: 
          name: security_scan.txt
          path: security_scan.txt
