mame: action workflow ci

on:
  push:
    branches:
      - main
      - feature

  pull_request:
    branches:
      - main

permissions:
  contents: read


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: GitLeaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
          cache: pip
          cache-dependency-path: "./requirements.txt"

      - name: Application tests
        uses: ./.github/actions/app-action
        with:
          dependency: requirements.txt
          pylint: true
          bandit: true
          flake8: true
          pytest: true
          unittest: true

      - name: Generate build information
        id: build_info
        uses: ./.github/actions/script-action
        with:
          application_name: hamza
          environment: development

      - name: Upload build information
        uses: actions/upload-artifact@v7
        with:
          name: build-info
          path: ${{ steps.build_info.outputs.build_info }}
          if-no-files-found: error


  docker-build:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Generate build information
        id: build_info
        uses: ./.github/actions/script-action
        with:
          application_name: hamza
          environment: development

      - name: Upload build information
        uses: actions/upload-artifact@v7
        with:
          name: build-info
          path: ${{ steps.build_info.outputs.build_info }}
          if-no-files-found: error

      - name: Build and Push Docker Image
        uses: ./.github/actions/build-action
        with:
          docker_username: ${{ vars.DOCKER_USERNAME }}
          docker_token: ${{ secrets.DOCKER_TOKEN }}
          image_name: ${{ vars.IMAGE_NAME }}
          image_tag: ${{ github.sha }}


  docker-security:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Generate build information
        id: build_info
        uses: ./.github/actions/script-action
        with:
          application_name: hamza
          environment: development

      - name: Upload build information
        uses: actions/upload-artifact@v7
        with:
          name: build-info
          path: ${{ steps.build_info.outputs.build_info }}
          if-no-files-found: error

      - name: Docker Security Scan
        uses: ./.github/actions/security-scan-action
        with:
          docker_username: ${{ vars.DOCKER_USERNAME }}
          docker_token: ${{ secrets.DOCKER_TOKEN }}
          image_name: ${{ vars.IMAGE_NAME }}
          image_tag: ${{ github.sha }}


  smoke-test:
    needs: docker-security
    runs-on: ubuntu-latest

    steps:
      - name: Generate build information
        id: build_info
        uses: ./.github/actions/script-action
        with:
          application_name: hamza
          environment: development

      - name: Upload build information
        uses: actions/upload-artifact@v7
        with:
          name: build-info
          path: ${{ steps.build_info.outputs.build_info }}
          if-no-files-found: error

      - name: Smoke Test
        uses: ./.github/actions/smoke-test-action
        with:
          docker_username: ${{ vars.DOCKER_USERNAME }}
          docker_token: ${{ secrets.DOCKER_TOKEN }}
          image_name: ${{ vars.IMAGE_NAME }}
          image_tag: ${{ github.sha }}

  deployment:
    needs: smoke-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Generate build information
        id: build_info
        uses: ./.github/actions/script-action
        with:
          application_name: hamza
          environment: development

      - name: Upload build information
        uses: actions/upload-artifact@v7
        with:
          name: build-info
          path: ${{ steps.build_info.outputs.build_info }}
          if-no-files-found: error

      - name: Docker Compose Deployment Test
        uses: ./.github/actions/compose-action
        with:
          docker_username: ${{ vars.DOCKER_USERNAME }}
          docker_token: ${{ secrets.DOCKER_TOKEN }}
          image_name: ${{ vars.IMAGE_NAME }}
          image_tag: ${{ github.sha }}